Do not run check-llvm on Darwin
Bug: http://b/326166097

check-llvm-unittests is broken due to
> dyld: Symbol not found: __ZNKSt3__115basic_stringbufIcNS_11char_traitsIcEENS_9allocatorIcEEE3strEv

Disable check-llvm since it is not possible to disable only check-llvm-unittests.

Change-Id: I8ac746cb75f3107de7e9ed14cd01e55b9714f56b
Test: postsubmit